# Generated by Django 6.0.1 on 2026-02-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_transaction_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='upi_id',
            field=models.CharField(blank=True, help_text='Your UPI VPA', max_length=50, null=True),
        ),
    ]
