# Generated by Django 6.0.1 on 2026-02-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='source_message',
            field=models.TextField(blank=True, help_text='Original SMS or notification content', null=True),
        ),
    ]
