# Generated by Django 6.0.1 on 2026-02-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_transaction_source_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_id_tracking',
            field=models.CharField(blank=True, help_text='Razorpay/Gateway Payment ID for tracking', max_length=100, null=True, unique=True),
        ),
    ]
