# Generated by Django 6.0.1 on 2026-02-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
