# Generated by Django 6.0.1 on 2026-02-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_userprofile_notifications_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='payment_id_tracking',
        ),
        migrations.AddField(
            model_name='transaction',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
